### ISSUE TITLE
Problem with CustomRenderTexture

### ISSUE THREAD

**Issue by wyb969** [hecomi/UnityWaterSurface#1]
The project in my PC can't work. It  report a error about "Custom Render Texture". The console shows that
"error CS0246: The type or namespace name `CustomRenderTexture' could not be found".
 I have write the using UnityEngine. So, I'm very confused. My unity Edition is 5.6.0f3(64 bit)...
So, I'm really hoping you can help me with this problem. Thank you.

**Comment by hippocoder** [comment]
This feature is introduced in 2017.1 so it will not work for you.

https://docs.unity3d.com/Manual/CustomRenderTextures.html

**Comment by wyb969** [comment]
well, thanks,  I find the difference about Edition. By the way , Could I make the water ripple effect on the lower Edition ? Can I use the Render Texture to replace the Custom Render Texture? Thanks ,again.

**Comment by hecomi** [comment]
Yes you can. `CustomRenderTexture` is a alias to use `RenderTexture` to be able to refer it as `_SelfTexture2D`. If you can create `RenderTexture` by yourself and give it to your shader`, you can do the same thing as this demo.
