### ISSUE TITLE
where can I find the Algrithm 

### ISSUE THREAD

**Issue by doremi31618** [hecomi/UnityWaterSurface#3]
Hi, Thanks for this amazing works, I am studying water wave simulation and want to study further, can I ask for the algorithm you use, or where can I find it?

p.s. if there have any tutorials of this algorithm will be very helpful

thanks a lot

**Comment by hecomi** [comment]
I used a simple 2-dimentional wave equation. I wrote a blog article about this asset and put a link to the reference site:
- http://tips.hecomi.com/entry/2017/05/17/020037
- https://qiita.com/tobira-code/items/a6ff685dc99a6fee2f92
(Both are written in Japanese so please translate them into your language using Google Translate or something if needed).

**Comment by doremi31618** [comment]
Ah gotcha . it’s very helpful ! Thank you for clearing that up =)
